### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Drachenkaetzchen** [obiwanjacobi/vst.net#13]
Hi,

I just noticed that the license for vst.net is missing. Using the [wayback machine](http://web.archive.org/web/20171225153255/https://vstnet.codeplex.com/license) I found out that this library is licensed under the LGPL V2.1 license. Should I create a PR to include the LGPL v2.1 license or do you have plans to change it to something else?

**Comment by obiwanjacobi** [comment]
If you could add the LGPL v2.1 license for now, that would be great. Thanx.

**Comment by obiwanjacobi** [comment]
fixed it.
