### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by techtim** [obiwanjacobi/vst.net#14]
Is it possible or somebody tried to implement a cross-platform plugin using the lib? Looks really topical  with current net core growing popularity

**Comment by obiwanjacobi** [comment]
There is unmanaged code to interface with the VST C API that uses the Microsoft C++ extensions. I don't think that is possible...
But I haven't looked into dotnet core in great detail yet.

**Comment by MelbourneDeveloper** [comment]
@techtim my thinking is that it would be possible but you'd have to take the existing C++ code and make Windows specific code compile for MacOS. .NET Core is easy to get working on Mac.

**Comment by obiwanjacobi** [comment]
The C++/CLI support for dotnet-core is Windows only at this time.
