### ISSUE TITLE
Midi Event Note Duration

### ISSUE THREAD

**Issue by mikech2000** [obiwanjacobi/vst.net#17]
Thanks for your work on vst.net. 
I am finding that the VstMidiEvent.NoteLength is always zero, even when playing back recorded MIDI events. I am using Reaper. Is this a Reaper problem, or is this just not going to work with any DAW?

**Comment by obiwanjacobi** [comment]
Yeah, length is notoriously not supported by most hosts. Even if supported, its always zero when notes are played in real-time (live).
Best way to determine note length is to track note-on and note-off message for the same note-number.
