### ISSUE TITLE
"[DLL] failed to load!"

### ISSUE THREAD

**Issue by nachomartinez80** [obiwanjacobi/vst.net#19]
Hi, thanks for this great tool.
I'm having some trouble trying to load almost any VST DLL, regardless if it's x86 or x64.

This is for VstPluginContext.Create(). I'm using one of AudioVSTToolbox's applications.

Anything I should know about the type of DLL that the code accepts? I'm trying with Waves and Izotope.

**Comment by obiwanjacobi** [comment]
What is the error text (stack trace)?
Is the dll you're trying to load 32- or 64-bit?

In general loading .dll's may also fail if a dependent dll cannot be found. Try with a simple VST that has all its dependencies in one folder for instance.

**Comment by nachomartinez80** [comment]
hi, thanks for answering!
it's a 64 bit DLL in this case. The thing is that Waves uses a Shell DLL
and then from it calls the other sub libraries which are other DLLs... not
sure how to make it work in that case... it's designed for DAW
functionalities. but also pretty much all of the other libraries I want to
use are pretty much designed this way...

Main Waves library: C:\Program Files\VSTPlugIns\WaveShell-VST 9.2_x64.dll
My desired library: C:\Program Files (x86)\Waves\Plug-Ins
V9\L2.bundle\Contents\Win64\L2.dll (throws error)

the stack trace is in French, not sure you'll understand but i'll copy it
here below. not sure if it's what you need:













*'ProcessVSTPlugin2.exe' (CLR v4.0.30319: DefaultDomain) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: DefaultDomain) : Chargé
'C:\Users\IMA\Downloads\AudioVSTToolbox-master\AudioVSTToolbox-master\ProcessVSTPlugin2\bin\Debug\ProcessVSTPlugin2.exe'.
Les symboles ont été chargés.'ProcessVSTPlugin2.exe' (CLR v4.0.30319:
ProcessVSTPlugin2.exe) : Chargé
'C:\Users\IMA\Downloads\AudioVSTToolbox-master\AudioVSTToolbox-master\ProcessVSTPlugin2\bin\Debug\CommonUtils.dll'.
Le module a été généré sans symboles.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Users\IMA\Downloads\AudioVSTToolbox-master\AudioVSTToolbox-master\ProcessVSTPlugin2\bin\Debug\NAudio.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Users\IMA\Downloads\AudioVSTToolbox-master\AudioVSTToolbox-master\ProcessVSTPlugin2\bin\Debug\Jacobi.Vst.Core.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Users\IMA\Downloads\AudioVSTToolbox-master\AudioVSTToolbox-master\ProcessVSTPlugin2\bin\Debug\Jacobi.Vst.Interop.dll'.
Le module a été généré sans symboles.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'.
Chargement des symboles ignoré. Le module est optimisé et l'option du
débogueur 'Uniquement mon code' est activée.'ProcessVSTPlugin2.exe' (CLR
v4.0.30319: ProcessVSTPlugin2.exe) : Chargé
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_fr_b77a5c561934e089\mscorlib.resources.dll'.
Le module a été généré sans symboles.Exception levée :
'System.ArgumentException' dans Jacobi.Vst.Interop.dll*

**Comment by obiwanjacobi** [comment]
That looks more like an output while loading the dll's by the process (or debugger) saying it cannot find any symbols (if I interpreted the French text correctly).

Something else came to mind: Are you sure these plugins are not VST 3.x? Because VST.NET only supports VST 2.x! 

If you open the VST plugin dll you want to load in a tool/utility that shows the exported functions (Dll Export Viewer for instance) you should see `main` or `VSTPluginMain` (as I do for VST.NET plugins: https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/Jacobi.Vst.Interop.def).
If I remember correctly VST 3.x works with different exports (https://github.com/obiwanjacobi/vst.net/blob/master/Source3/Code/Jacobi.Vst3.TestPlugin/Exports.cs).

Finally if you have verified the plugin is VST 2.x make sure you compile the interop as x64. The GetProcAddress API call I use should then be able to load x64 dll's. 
https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/Host/VstUnmanagedPluginContext.cpp

(disclaimer: it's been years so I lost some of the detailed knowledge)

**Comment by nachomartinez80** [comment]
I'll look into all og that, thanks again for taking the time
