### ISSUE TITLE
Samples not working

### ISSUE THREAD

**Issue by gunnerwolf** [obiwanjacobi/vst.net#2]
I built a couple of the samples (Namely Delay and MIDI Sampler) as x64 Release in VS2017, and attempted to load them as VST plugins into VSTHost, FL Studio, and a custom host I made using VST.NET.

On all 3 hosts the plugin failed to load claiming entry point not found.

I have made sure the plugin properly references the VST.NET libraries, and that all DLLs are in the same folder.

I also encountered this same issue when creating my own VST plugin with VST.NET

**Comment by obiwanjacobi** [comment]
Did you read:
https://github.com/obiwanjacobi/vst.net/blob/master/Using%20VST.NET.md

The EntryPoint is in the Interop assembly and you have to point your DAW/Host to that (renamed) file to load the VST.NET plugin.
