### ISSUE TITLE
Discord server link broken

### ISSUE THREAD

**Issue by thechrisgeorgiev** [obiwanjacobi/vst.net#24]
The discord server link in readme has expired

**Comment by obiwanjacobi** [comment]
https://discord.gg/n7RDqG

**Comment by Manu404** [comment]
Hi, wanted too to join, url "https://discord.gg/n7RDqG" gives "invalid or expired" error :(

**Comment by obiwanjacobi** [comment]
https://discord.gg/QyZqQDk

**Comment by obiwanjacobi** [comment]
I found the 'never expire' option ;-)
