### ISSUE TITLE
Functionality of ShellCreate / Support for Waves Shell Plugins

### ISSUE THREAD

**Issue by verystack** [obiwanjacobi/vst.net#26]
Is PluginContext.ShellCreate() to use Waves-style shell plugins?
How is it meant to be instantiated?

If not, what is it used for?

**Comment by obiwanjacobi** [comment]
Not familiar with 'Waves' but if I remember correctly (last worked on this 7 years ago) it allows a single plugin dll to contain multiple plugins (to the Host/DAW). It works in conjunction with (on the main/root plugin loaded first) GetNextPlugin() and I think there was also a Flag a 'shell plugin' has to set in order for the Host to know to call the GetNextPlugin().

The ShellCreate is called on the main/root PluginContext after the GetNextPlugin call was issued - I think. It is only implemented for unmanaged plugins and as far as I know I never really tested this through. So disclaimer ;-)

**Comment by obiwanjacobi** [comment]
Closing - discussion seems to be done.
