### ISSUE TITLE
Several links in the readme are broken.

### ISSUE THREAD

**Issue by rokit** [obiwanjacobi/vst.net#3]

**Comment by obiwanjacobi** [comment]
I know, the migration from codeplex was a mess.
View the docs at the codeplex site as a workaround.

**Comment by iiian** [comment]
Codeplex really wants to redirect to github.  at the risk of being that guy who didn't look hard enough, I'm going to proclaim that it... may not be possible.  Thanks a ton for VST.NET though!!!

**Comment by Drachenkaetzchen** [comment]
I think this issue can be closed, PR was merged

**Comment by obiwanjacobi** [comment]
Right. Thanks for your work.
