### ISSUE TITLE
System.BadImageFormatException when launching Samples.Host

### ISSUE THREAD

**Issue by fgoulet** [obiwanjacobi/vst.net#30]
I got this exception when starting Jacobi.Vst.Samples.Host in debug. I tried with both configuration x86 and x64.

System.BadImageFormatException Message=Could not load file or assembly 'Jacobi.Vst.Host.Interop, Version=2.0.0.0

I have Microsoft Visual C++ 2015-2019 Redistributable version 14.27.28914.0 installed,  x86 and x64.

Any idea what I could be missing ?

**Comment by obiwanjacobi** [comment]
Yeah, sorry about that. I have been focusing on the Plugin side of things mainly.
There is a small problem with the Nuget package linkage to the project.
Anyway, quick fix is to copy the `Ijwhost.dll` next the .exe.
You can find it in 'deploy' sub folder.

**Comment by fgoulet** [comment]
Thanks, it works now.

**Comment by obiwanjacobi** [comment]
Excellent
