### ISSUE TITLE
Command " publish" not found

### ISSUE THREAD

**Issue by dodinhhoanganh** [obiwanjacobi/vst.net#38]
I try to build my project after adding VST.Net and I got the error: 
The command " publish "C:\Users\ngoan\source\repos\RMVN Studio\RMVN Studio\bin\x64\Debug\RMVN Studio.exe" -o "C:\Users\ngoan\source\repos\RMVN Studio\RMVN Studio\bin\x64\Debug\deploy"" exited with code 9009.
It mean command publish not found, so how can I fix it?
It only happend when I add VST.Net library, previous build without VST.Net not contain any error.
Please help me! Btw, sorry for my bad English!

**Comment by dodinhhoanganh** [comment]
So, I was fixed this issue by install older version which support .net framework
Because new version only support .net core xD

**Comment by obiwanjacobi** [comment]
FYI
The problem was that you've added the VST2 (core) package to a .NET Fx 4.x project.
The build file (in the VST2 package) did not handle that situation gracefully.
I have tried to fix it in the build file to generate a compiler error in that situation.
