### ISSUE TITLE
vst.net plugin throws ArgumentException when receiving MIDI events

### ISSUE THREAD

**Issue by moosmartin** [obiwanjacobi/vst.net#47]
**Describe the bug**
When I compile the sample MIDI plugin and load it in a DAW, the plugin throws the following exception each time I sent MIDI note data to it:
```
System.ArgumentException: The specified eventType is not generic (deprecated). (Parameter 'eventType')
   at Jacobi.Vst.Core.Legacy.VstGenericEvent..ctor(VstEventTypes eventType, Int32 deltaFrames, Byte[] data) in C:\Users\[...]\vst.net\Source\Code\Jacobi.Vst.Core\Legacy\VstGenericEvent.cs:line 22
   at TypeConverter.ToManagedEventArray(Vst2Events* pEvents)
   at Jacobi.Vst.Plugin.Interop.PluginCommandProxy.Dispatch(Int32 opcode, Int32 index, Int32 value, Void* ptr, Single opt)
```

**To Reproduce**
1. Load sample MIDI plugin (`Jacobi.Vst.Samples.MidiNoteMapper.dll`) in a DAW (tested with Ableton Live and Bitwig Studio)
2. Send MIDI data to plugin

**Expected behavior**
The plugin processes the MIDI data

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
The sample audio plugin (`Jacobi.Vst.Samples.Delay.dll`) works as expected.
I tried debugging into the plugin with Visual Studio 2019 after compiling the library code with the Debug configuration, but cannot get any breakpoints to trigger.

**Comment by obiwanjacobi** [comment]
Ooops! Thanks for reporting.

To help you continue with your progress:
- locate the `Vst2400.h` file in the `Jacobi.Vst.Plugin.Interop` project.
- goto line 260 (inside the `Vst2EventKind` enum)
- Add a `None` option before the `Midi` option.
- (re)build the solution

Will be fixed in next version.
Hope this helps.
