### ISSUE TITLE
How to use locally compiled version of Jacobi.Vst.Plugin.Interop

### ISSUE THREAD

**Issue by trondhindenes** [obiwanjacobi/vst.net#48]
**Describe the bug**
Trying to use the locally built version of the library (#47) in the midi sample project, but failing

**To Reproduce**
I've cloned vst.net and built the solution, so I have an "x64" folder with generated dlls. Now I'm trying to set up the midi sample template so that it's using these dlls instead of the regular vst.net nuget package. I've tried via the regular "add assemblies --> browse" dialog, the project doesnt build. 

It would be awesome to have either
- an updated version of the library pushed to nuget where the "midi fix" is in, or
- detailed instructions for how to use the locally built vst.net libraries in the sample project

**Comment by obiwanjacobi** [comment]
You could try to copy the new Jacobi.Vst.Plugin.Interop over your local nuget version that is at `C:\Users\[user]\.nuget\packages\vst.net2-plugin\2.0.0-rc3\lib\netcoreapp3.1\x64`

**Comment by trondhindenes** [comment]
oh - thanks. I Should have thought of that.

**Comment by obiwanjacobi** [comment]
The new VST.NET 2 package (>=v2.0.0) has the fix in it.
