### ISSUE TITLE
VST host. Is it possible to change VstAudioBufferManager buffer size in the fly?

### ISSUE THREAD

**Issue by izmopa** [obiwanjacobi/vst.net#5]
First thanks! Really great work! I got my realtime host process working fine. But I have one question.

I have vst input and output VstAudioBufferManager buffer size fixed to 1920. Everything works perfectly.
But I need also support in my application to changing buffer size. For example first sample have size 1602, next size 1601 and so on. Is it possible to change VstAudioBufferManager buffer size on the fly?

**Comment by obiwanjacobi** [comment]
I would suggest you use one buffer manager for all the fixed buffers and a separate buffer manager for the dynamic ones. You may also consider just allocating the largest buffer size and pass them as smaller ones. This has some unused memory overhead but may be a better choice that dynamically reallocating memory during processing - which will certainly impact performance.

**Comment by izmopa** [comment]
In my tests if I pass less samples to VST buffers (for example 1601) that I have defined to input and output VstAudioBufferManager causes distortion to processed audio.
using (inputMgr = new VstAudioBufferManager(1602))...

I haven't tryed yet more VstAudioBufferManager than one input and output manager.

**Comment by izmopa** [comment]
I had fault in my code. Yes I can pass now less samples to VST buffers as I have allocated to buffers in VstAudioBufferManager. No distortions! Thanks a lot!

**Comment by obiwanjacobi** [comment]
> using (inputMgr = new VstAudioBufferManager(1602))...

This code suggests that the lifetime of your buffer manager is scoped. That (probably) means that you are (re)allocating memory during processing. Do not do that. create one buffer manager instance and keep the reference at a global place (the app object?) and refer to that one instance. When host settings change (buffer size etc) recreate that one instance.
