### ISSUE TITLE
Could not find nuget package location.

### ISSUE THREAD

**Issue by Becks723** [obiwanjacobi/vst.net#50]
Failed to build my host project after adding the host package. 
I tried to look into error details, then i found the command line did not find my correct nuget path.

see:
https://github.com/obiwanjacobi/vst.net/blob/33283e85eb80f74b39fb472d844a01ebda387b8a/Source/Code/Jacobi.Vst.CLI/FileExtensions.cs#L8

Some time before i moved my package location to D disk because my C disk is too full. It's now on "D:\.nuget\packages". So what should i do to make command line recognize the new location?

**Comment by obiwanjacobi** [comment]
As you can see the location of the nuget packages is hard-coded.
How did you change the nuget package location?

**Comment by Becks723** [comment]
1. first move the .nuget folder to the destination (in my case D:\.nuget)
2. next modify nuget.config (located in C:\Users\Becks723\AppData\Roaming\NuGet in my case):
 add xml node `<config> <add key="globalPackagesFolder" value="D:\.nuget\Packages" /> </config>`, then save. Done.

But i'm now not using the nuget package but building my custom dll.

Just suppose better ways instead of the hardcoded location, to get user-specific nuget path. However currently I don't have any idea about it.

**Comment by obiwanjacobi** [comment]
Thanks. Agree that hardcoding the path is sub-optimal. I think I will try to read the nuget config as well...
I see there is also an environment variable that Nuget supports: NUGET_PACKAGES. Perhaps I can support that too.

**Comment by obiwanjacobi** [comment]
Will be fixed in next release.
https://github.com/obiwanjacobi/vst.net/blob/75bc44e4e13d7827377e660fd3fc28641132ce81/Source/Code/Jacobi.Vst.CLI/FileExtensions.cs#L8

**Comment by obiwanjacobi** [comment]
VST.NET2 v2.03 should fix this.
