### ISSUE TITLE
TimeInfo properties not changing specifically in FL Studio

### ISSUE THREAD

**Issue by SixBeeps** [obiwanjacobi/vst.net#54]
**Describe the bug**
The time properties provided by the host sequencer's TimeInfo instance (working with the default delay sample, look at AudioProcessor.TimeInfo) do not appear to be changing, even when the song is played

**To Reproduce**
1.) Open any other DAW, I used both Ableton Live 10 Lite and Cantabile 3.0.
2.) Load the plugin as an effect and play some notes, time-based processing works.
3.) Open FL Studio and load the same effect onto a track.
3.) Play some notes, time does not affect processing.

**Expected behavior**
`TimeInfo.PpqPosition` and other related properties return what they say they do

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome

**Additional context**
To further explain how I know these values aren't changing, here are some relevant snippets of code from my plugin.

From AudioProcessor.cs:
```cs
private float GetBeatProgress() {
        return (float)(TimeInfo.PpqPosition % 1f);
}
```

From Heart.cs, the class which handles my plugin's logic:
```cs
// The result of GetBeatProgress() is passed on as beatProgress
public float ProcessSample(float sample, float beatProgress) {
        float pumpPercent = _parameters.PumpAmtMgr.CurrentValue / 100f;
        float output = sample * pumpPercent * beatProgress;
        return output;
}
```

This plugin applies a fake sidechain effect to the given signal. This works fine in other DAWs, but FL Studio in particular returns an empty signal. Furthermore, removing the beatProgress multiplier outputs a clean signal. Therefore, beatProgress is somehow kept constant at 0.

**Comment by obiwanjacobi** [comment]
What value do you have specified for [`_defaultTimeInfoFlags`](https://github.com/obiwanjacobi/vst.net/blob/73b8640fefc11d44e9d59b631918cfaba13beb09/Source/Templates/CSharp/VstNetAudioPlugin/AudioProcessor.cs#L29)?
If you want `ppq` to be valid you have to specify the [`PpqPositionValid` enum value](https://github.com/obiwanjacobi/vst.net/blob/73b8640fefc11d44e9d59b631918cfaba13beb09/Source/Code/Jacobi.Vst.Core/VstTimeInfo.cs#L117) in `_defaultTimeInfoFlags`.

**Comment by SixBeeps** [comment]
> What value do you have specified for [`_defaultTimeInfoFlags`](https://github.com/obiwanjacobi/vst.net/blob/73b8640fefc11d44e9d59b631918cfaba13beb09/Source/Templates/CSharp/VstNetAudioPlugin/AudioProcessor.cs#L29)? If you want `ppq` to be valid you have to specify the [`PpqPositionValid` enum value](https://github.com/obiwanjacobi/vst.net/blob/73b8640fefc11d44e9d59b631918cfaba13beb09/Source/Code/Jacobi.Vst.Core/VstTimeInfo.cs#L117) in `_defaultTimeInfoFlags`.

I had it set to the default `VstTimeInfoFlags.ClockValid`, but changing it to the value you mentioned didn't seem to have an effect.

**Comment by SixBeeps** [comment]
Ahh, it started working all of a sudden. Guess that change actually did work. Thanks!
