### ISSUE TITLE
Discord invite link is stale

### ISSUE THREAD

**Issue by ianloic** [obiwanjacobi/vst.net#59]
When I tried to join I got an error: 
**WRONG TURN?**
You look lost, stranger. You know what helps when you’re lost? A piping hot bowl of noodles. Take a seat, we’re frantically at work here cooking up something good. Oh, you need something to read? These might help you:

**Comment by obiwanjacobi** [comment]
I got the same page (not sure if or what the error is) when I tried the link.
Then tried to generate a new link in Discord, but an unlimited link, always results in the same code.
Just now tried again, now it seems to work.
Go figure.

So, please try again and tell us how it went...

**Comment by ianloic** [comment]
Well, I got the error, but it also put me on the server at some point, so who knows...
