### ISSUE TITLE
Is there any demo project using NAudio and VST.NET?

### ISSUE THREAD

**Issue by tom-23** [obiwanjacobi/vst.net#6]
Is there a demo project for a VST Host using NAudio? I haven't managed to find one.

**Comment by obiwanjacobi** [comment]
No there is not. How are you using NAudio?
Perhaps my MIDI.NET project may also be of use?

**Comment by crabstick-x** [comment]
I am trying to add VST audio effects to a NAudio stream. Is there any documentation or code examples on a VST host?

**Comment by obiwanjacobi** [comment]
The old discussion archives over at codeplex have some info on this. Search for naudio in the discussion list.
https://archive.codeplex.com/?p=vstnet

There is a Host sample that demonstrates the VST.NET host API. It is not a working host.
https://github.com/obiwanjacobi/vst.net/tree/master/Source/Samples/Jacobi.Vst.Samples.Host

**Comment by Drachenkaetzchen** [comment]
It seems that [AudioVSTToolbox](https://github.com/perivar/AudioVSTToolbox/tree/master/ProcessVSTPlugin2) uses some NAudio stuff, maybe you can have a look there.
