### ISSUE TITLE
.NET6 Support

### ISSUE THREAD

**Issue by obiwanjacobi** [obiwanjacobi/vst.net#60]
Bump all projects, samples and templates to .NET6
Also update the C++ to the latest runtime distributable.

**Comment by paulpv** [comment]
The update seems pretty transparent.
I just updated my fork.
https://github.com/NightVsKnight/vst.net/commit/e7f2cc3e94604e528772d2977eaa93edfd016843

**Comment by obiwanjacobi** [comment]
Fixed in v2.1.0
